= Apache SIS ISO 19115-3 Update

=== Known Issues

*   TemporalExtent element does not map properly, and causes a warning in SIS.
*   Elements with the deprecated GMI namespace will use the new MDS namespace when marshalling to ISO 19115-3. There is no definitive answer as to whether this is correct until ISO 19115-4 is released. The decision to use the MDS namespace was made based on information gathered from page 8 of the ISO 19115-3 specification.
*   Related to the above, deprecated elements with the *MI_* prefix (which should generally now have the prefix *MD_*) still retain their old names. This could be fixed relatively easily in the *FilteredStreamReader* class, but I have decided to leave the element names as is until ISO 19115-4 is released.

=== Potential Issues

*   Any classes without _full_ (i.e. comprehensive) XML examples in this document may not have been fully tested due to time constraints. They should be the first place to look when a bug appears.

=== Testing

*   All tests in the sis-metadata and sis-utility packages that deal with marshalling or unmarshalling should have been updated to test both ISO 19139 and ISO 19115-3.
*   All tests should run and pass as expected.

=== Other Important Information

*   Whenever updates are made to the Apache SIS ISO metadata model, it is imperative to run *ElementNamespaceWriter* in *org.apache.sis.internal.jaxb*. After doing this, copy the *ElementNamespaceMap.txt* file from _src/main/resources_ in the *sis-metadata* package into the _src/main/resources_ folder in the *sis-utility* package. Otherwise, (un)marshalling of metadata may not work properly.

=== Change Log

.Updates to ISO 19139 elements
[cols="e,a,a,a,a",width="100%", options="header"]
|====================
|ISO 19139 XML Tag | Modified Java Classes | Changes | ISO 19139 Example | ISO 19115-3 Example


| [[MD_Metadata]] MD_Metadata
|
*   DefaultMetadata
|
*   Namespace is now "mdb" from "gmd"
*   New elements include _metadataIdentifier_, _defaultLocale_, _parentMetadata_, _dateInfo_, _metadataStandard_, _metadataProfile_, _alternativeMetadataReference_, _otherLocale_, _metadataLinkage_, and _resourceLineage_
*   Deprecated elements include _fileIdentifier_, _language_, _characterSet_, _parentIdentifier_, _hierarchyLevel_, _hierarchyLevelName_, _dateStamp_, _metadataStandardName_, _metadataStandardVersion_, _dataSetURI_, and _locale_
*   Many of the above elements appear as their own entries in the table
|
[source,xml]
----
<gmd:MD_Metadata>
  ...
</gmd:MD_Metadata>
----
|
[source,xml]
----
<mdb:MD_Metadata>
  ...
</mdb:MD_Metadata>
----



| [[fileIdentifier]] fileIdentifier
|
*   DefaultMetadata
*   DefaultIdentifier
|
*   Name is now _metadataIdentifier_
*   Namespace is now "mdb" from "gmd"
*   Original _CharacterString_ element now wrapped inside _mcc:code_ inside _mcc:MD_Identifier_
|
[source,xml]
----
<gmd:fileIdentifier>
  <gco:CharacterString>my_id</gco:CharacterString>
</gmd:fileIdentifier>
----
|
[source,xml]
----
<mdb:metadataIdentifier>
  <mcc:MD_Identifier>
    <mcc:code>
      <gco:CharacterString>my_id</gco:CharacterString>
    </mcc:code>
  </mcc:MD_Identifier>
</mdb:metadataIdentifier>
----



| [[language]] language
|
*   DefaultMetadata
*   PT_Locale
*   LanguageCode
|
*   Namespace is now "lan" from "gmd"
*   Original _language_ element now wrapped inside _lan:PT_Locale_ inside _mdb:defaultLocale_
*   Now grouped with _lan:characterEncoding_ (see xref:characterSet[characterSet])
|
[source,xml]
----
<gmd:language>
  <gco:CharacterString>eng; USA</gco:CharacterString>
</gmd:language>
----
|
[source,xml]
----
<mdb:defaultLocale>
  <lan:PT_Locale>
    <lan:language>
      <lan:LanguageCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#LanguageCode" codeListValue="eng" codeSpace="eng">English</lan:LanguageCode>
    </lan:language>
    <lan:country>
      <lan:CountryCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#Country" codeListValue="US" codeSpace="eng">United States</lan:CountryCode>
    </lan:country>
    <lan:characterEncoding>
      <lan:MD_CharacterSetCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_CharacterSetCode" codeListValue="utf8" codeSpace="eng">UTF-8</lan:MD_CharacterSetCode>
    </lan:characterEncoding>
  </lan:PT_Locale>
</mdb:defaultLocale>
----



| [[locale]] locale
|
*   DefaultMetadata
|
*   Namespace is now "mdb" from "gmd"
*   Renamed to _otherLocale_
*   Both _locale_ and _otherLocale_ can be repeated multiple times - each instance holds a language that is not the default
|
[source,xml]
----
<gmd:locale>
  <gmd:PT_Locale>
    ...
   </gmd:PT_Locale>
</gmd:locale>
----
|
[source,xml]
----
<mdb:otherLocale>
  <lan:PT_Locale>
    ...
  </lan:PT_Locale>
</mdb:otherLocale>
----



| [[PT_Locale]] PT_Locale
|
*   PT_Locale
*   Country
|
*   Namespace is now "lan" from "gmd"
*   Inner _Country_ element name changed to _CountryCode_
|
[source,xml]
----
<gmd:PT_Locale>
  <gmd:languageCode>
    <gmd:LanguageCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#LanguageCode" codeListValue="ger" codeSpace="eng">German</gmd:LanguageCode>
  </gmd:languageCode>
  <gmd:country>
    <gmd:Country codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#Country" codeListValue="DE" codeSpace="eng">Germany</gmd:Country>
  </gmd:country>
  <gmd:characterEncoding>
    <gmd:MD_CharacterSetCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_CharacterSetCode" codeListValue="utf8" codeSpace="eng">UTF-8</gmd:MD_CharacterSetCode>
  </gmd:characterEncoding>
</gmd:PT_Locale>
----
|
[source,xml]
----
<lan:PT_Locale>
  <lan:language>
    <lan:LanguageCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#LanguageCode" codeListValue="ger" codeSpace="eng">German</lan:LanguageCode>
  </lan:language>
  <lan:country>
    <lan:CountryCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#Country" codeListValue="DE" codeSpace="eng">Germany</lan:CountryCode>
  </lan:country>
  <lan:characterEncoding>
    <lan:MD_CharacterSetCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_CharacterSetCode" codeListValue="utf8" codeSpace="eng">UTF-8</lan:MD_CharacterSetCode>
  </lan:characterEncoding>
</lan:PT_Locale>
----



| [[characterSet]] characterSet
|
*   DefaultMetadata
*   PT_Locale
*   MD_CharacterSetCode
|
*   Name is now _characterEncoding_
*   Namespace is now "lan" from "gmd"
*   Renamed element now wrapped inside _lan:PT_Locale_ inside _mdb_defaultLocale_
*   Now grouped with _lan:language_ (see xref:language[language])
*   NOTE: For now, the ISO 19115-3 _characterEncoding_ is always the default "UTF-8". I'm not sure how to change this, because I'm not sure how to properly pair two _characterEncoding_ and _language_ elements -- they seem logically unrelated to each other.
|
[source,xml]
----
<gmd:characterSet>
  <gmd:MD_CharacterSetCode
    codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_CharacterSetCode"
    codeListValue="utf8">utf8</gmd:MD_CharacterSetCode>
</gmd:characterSet>
----
|
See xref:language[language] ISO 19115-3 XML example.



| [[hierarchyLevel]] hierarchyLevel
|
*   DefaultMetadata
|
*   Renamed to _resourceScope_
*   Namespace is now "mdb" from "gmd"
*   _MD_ScopeCode_ namespace is now "mcc" from "gmd" 
*   Combined with xref:hierarchyLevelName[hierarchyLevelName] to form the new _MD_MetadataScope_ element, wrapped inside the _metadataScope_ tag
|
[source,xml]
----
<gmd:hierarchyLevel>
  <gmd:MD_ScopeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_ScopeCode" codeListValue="dataset">dataset</gmd:MD_ScopeCode>
</gmd:hierarchyLevel>
----
|
[source,xml]
----
<mdb:metadataScope>
  <mdb:MD_MetadataScope>
    <mdb:resourceScope>
      <mcc:MD_ScopeCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_ScopeCode" codeListValue="dataset" codeSpace="eng">Dataset</mcc:MD_ScopeCode>
    </mdb:resourceScope>
      <mdb:name>
        <gco:CharacterString>test_hierarchyLevelName</gco:CharacterString>
      </mdb:name>
  </mdb:MD_MetadataScope>
</mdb:metadataScope>
----



| [[hierarchyLevelName]] hierarchyLevelName
|
*   DefaultMetadata
|
*   Renamed to _name_
*   Namespace is now "mdb" from "gmd"
*   Combined with xref:hierarchyLevel[hierarchyLevel] to form the new _MD_MetadataScope_ element, wrapped inside the _metadataScope_ tag.
|
[source,xml]
----
<gmd:hierarchyLevelName>
  <gco:CharacterString>test_hierarchyLevelName</gco:CharacterString>
</gmd:hierarchyLevelName>
----
|
See xref:hierarchyLevel[hierarchyLevel] ISO 19115-3 XML example.



| [[CI_ResponsibleParty]] CI_ResponsibleParty
|
*   DefaultMetadata
*   DefaultResponsibility
*   CI_ResponsibleParty
|
*   Name changed to _CI_Responsibility_
*   Namespace is now "cit" from "gmd"
*   _organisationName_ and _individualName_ replaced by a _name_ element inside _CI_Organisation_ and _CI_Individual_ respectively.
*   _positionName_ moved inside CI_Individual
*   _CI_Individual_ and _CI_Organisation_ each now wrapped inside a _party_ element.
|
[source,xml]
----
<gmd:CI_ResponsibleParty>
  <gmd:individualName>
    <gco:CharacterString>Rick Sanchez</gco:CharacterString>
  </gmd:individualName>
  <gmd:organisationName>
    <gco:CharacterString>The Council of Ricks</gco:CharacterString>
  </gmd:organisationName>
  <gmd:positionName>
    <gco:CharacterString>Interdimensional Genius</gco:CharacterString>
  </gmd:positionName>
  <gmd:role>
    <gmd:CI_RoleCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#CI_RoleCode" codeListValue="owner" codeSpace="eng">Owner</gmd:CI_RoleCode>
  </gmd:role>
</gmd:CI_ResponsibleParty>
----
|
[source,xml]
----
<cit:CI_Responsibility>
      <cit:role>
        <cit:CI_RoleCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#CI_RoleCode" codeListValue="owner" codeSpace="eng">Owner</cit:CI_RoleCode>
      </cit:role>
      <cit:party>
        <cit:CI_Individual>
          <cit:name>
            <gco:CharacterString>Rick Sanchez</gco:CharacterString>
          </cit:name>
          <cit:positionName>
            <gco:CharacterString>Interdimensional Genius</gco:CharacterString>
          </cit:positionName>
        </cit:CI_Individual>
      </cit:party>
      <cit:party>
        <cit:CI_Organisation>
          <cit:name>
            <gco:CharacterString>The Council of Ricks</gco:CharacterString>
          </cit:name>
        </cit:CI_Organisation>
      </cit:party>
    </cit:CI_Responsibility>
----



| [[PT_FreeText]] PT_FreeText
|
*   PT_FreeText
*   TextGroup
|
*   Namespace is now "lan" from "gmd"
|
[source,xml]
----
<gmd:PT_FreeText>
  <gmd:textGroup>
    <gmd:LocalisedCharacterString locale="#locale-esp">Spanish Name</gmd:LocalisedCharacterString>
  </gmd:textGroup>
  <gmd:textGroup>
    <gmd:LocalisedCharacterString locale="#locale-ger">German Name</gmd:LocalisedCharacterString>
  </gmd:textGroup>
</gmd:PT_FreeText>
----
|
[source,xml]
----
<lan:PT_FreeText>
  <lan:textGroup>
    <lan:LocalisedCharacterString locale="#locale-esp">Spanish Name</lan:LocalisedCharacterString>
  </lan:textGroup>
  <lan:textGroup>
    <lan:LocalisedCharacterString locale="#locale-ger">German Name</lan:LocalisedCharacterString>
  </lan:textGroup>
</lan:PT_FreeText>
----



| [[parentIdentifier]] parentIdentifier
|
*   DefaultMetadata
*   DefaultCitation
|
*   Name is now _parentMetadata_
*   Namespace is now "mdb" from "gmd"
*   Now contains a _CI_Citation_ object instead of just a _gco:characterString_, so it can hold more attributes
|
[source,xml]
----
<gmd:parentIdentifier>
  <gco:CharacterString>parentName</gco:CharacterString>
</gmd:parentIdentifier>
----
|
[source,xml]
----
<mdb:parentMetadata>
  <cit:CI_Citation>
    <cit:title>
      <gco:CharacterString>parentName/gco:CharacterString>
    </cit:title>
    <cit:identifier>
      <mcc:MD_Identifier>
        <mcc:code>
          <gco:CharacterString>parentName</gco:CharacterString>
        </mcc:code>
      </mcc:MD_Identifier>
    </cit:identifier>
  </cit:CI_Citation>
</mdb:parentMetadata>
----



| [[CI_Contact]] CI_Contact
|
*   DefaultContact
|
*   Namespace is now "cit" from "gmd"
*   Contains xref:CI_Telephone[CI_Telephone], xref:CI_Address[CI_Address], and xref:CI_OnlineResource[CI_OnlineResource] elements, which have all changed slightly
*   New optional element called _contactType_, stored as a _gco:characterString_
|
[source,xml]
----
<gmd:CI_Contact/>
  ...
  <gmd:hoursOfService>
    <gco:CharacterString>Weekdays 9:00 AM - 5:00 PM</gco:CharacterString>
  </gmd:hoursOfService>
  <gmd:contactInstructions>
    <gco:CharacterString>contactInstructions</gco:CharacterString>
  </gmd:contactInstructions>
<gmd:CI_Contact/>
----
See xref:CI_Telephone[CI_Telephone], xref:CI_Address[CI_Address], and xref:CI_OnlineResource[CI_OnlineResource] for the unspecified elements contained in CI_Contact.
|
[source,xml]
----
<cit:CI_Contact>
  ...
  <cit:hoursOfService>
    <gco:CharacterString>Weekdays 9:00 AM - 5:00 PM</gco:CharacterString>
  </cit:hoursOfService>
  <cit:contactInstructions>
    <gco:CharacterString>contactInstructions</gco:CharacterString>
  </cit:contactInstructions>
  <cit:contactType>
    <gco:CharacterString>contactType</gco:CharacterString>
  </cit:contactType>
</cit:CI_Contact>
----
See xref:CI_Telephone[CI_Telephone], xref:CI_Address[CI_Address], and xref:CI_OnlineResource[CI_OnlineResource]  for the unspecified elements contained in CI_Contact.



| [[CI_Telephone]] CI_Telephone
|
*   DefaultTelephone
*   CI_TelephoneTypeCode (new type adapter class)
|
*   Namespace is now "cit" from "gmd"
*   _voice_ element replaced with a pair of _number_ and _numberType_ elements. Same goes for the _facsimile_ element.
|
[source,xml]
----
<gmd:phone>
  <gmd:CI_Telephone>
    <gmd:voice>
      <gco:CharacterString>555-867-5309</gco:CharacterString>
    </gmd:voice>
    <gmd:facsimile>
      <gco:CharacterString>555-555-5555</gco:CharacterString>
    </gmd:facsimile>
  </gmd:CI_Telephone>
<gmd:phone>
----
|
[source,xml]
----
<cit:phone>
  <cit:CI_Telephone>
    <cit:number>
      <gco:CharacterString>555-867-5309</gco:CharacterString>
    </cit:number>
    <cit:numberType>
      <cit:CI_TelephoneTypeCode codeList="codeListLocation#CI_TelephoneTypeCode" codeListValue="voice">voice</cit:CI_TelephoneTypeCode>
    </cit:numberType>
  </cit:CI_Telephone>
</cit:phone>
<cit:phone>
  <cit:CI_Telephone>
    <cit:number>
      <gco:CharacterString>555-555-5555</gco:CharacterString>
    </cit:number>
    <cit:numberType>
      <cit:CI_TelephoneTypeCode codeList="codeListLocation#CI_TelephoneTypeCode" codeListValue="facsimile">facsimile</cit:CI_TelephoneTypeCode>
    </cit:numberType>
  </cit:CI_Telephone>
</cit:phone>
----



| [[CI_Address]] CI_Address
|
*   CI_Address (indirectly, only namespace changed)
|
*   Namespace is now "cit" from "gmd"
|
[source,xml]
----
<gmd:address>
  <gmd:CI_Address>
    <gmd:deliveryPoint>
      <gco:CharacterString>deliveryPoint</gco:CharacterString>
    </gmd:deliveryPoint>
    <gmd:city>
      <gco:CharacterString>exampleCity</gco:CharacterString>
    </gmd:city>
    <gmd:administrativeArea>
      <gco:CharacterString>administrativeArea</gco:CharacterString>
    </gmd:administrativeArea>
    <gmd:postalCode>
      <gco:CharacterString>postalCode</gco:CharacterString>
    </gmd:postalCode>
    <gmd:country>
      <gco:CharacterString>exampleCountry</gco:CharacterString>
    </gmd:country>
    <gmd:electronicMailAddress>
      <gco:CharacterString>test@example.com</gco:CharacterString>
    </gmd:electronicMailAddress>
  </gmd:CI_Address>
</gmd:address>
----
|
[source,xml]
----
<cit:address>
  <cit:CI_Address>
    <cit:deliveryPoint>
      <gco:CharacterString>deliveryPoint</gco:CharacterString>
    </cit:deliveryPoint>
    <cit:city>
      <gco:CharacterString>exampleCity</gco:CharacterString>
    </cit:city>
    <cit:administrativeArea>
      <gco:CharacterString>administrativeArea</gco:CharacterString>
    </cit:administrativeArea>
    <cit:postalCode>
      <gco:CharacterString>postalCode</gco:CharacterString>
    </cit:postalCode>
    <cit:country>
      <gco:CharacterString>exampleCountry</gco:CharacterString>
    </cit:country>
    <cit:electronicMailAddress>
      <gco:CharacterString>test@example.com</gco:CharacterString>
    </cit:electronicMailAddress>
  </cit:CI_Address>
</cit:address>
----



| [[CI_OnlineResource]] CI_OnlineResource
|
*   DefaultOnlineResource
*   CI_OnLineFunctionCode
|
*   Namespace is now "cit" from "gmd"
*   _linkage_ element is now stored as a _gco:characterString_ instead of a _gmd:URL_
|
[source,xml]
----
<gmd:onlineResource>
  <gmd:CI_OnlineResource>
    <gmd:linkage>
      <gmd:URL>http://example.com</gmd:URL>
    </gmd:linkage>
    <gmd:protocol>
      <gco:CharacterString>protocol</gco:CharacterString>
    </gmd:protocol>
    <gmd:applicationProfile>
      <gco:CharacterString>applicationProfile</gco:CharacterString>
    </gmd:applicationProfile>
    <gmd:name>
      <gco:CharacterString>name</gco:CharacterString>
    </gmd:name>
    <gmd:description>
      <gco:CharacterString>description</gco:CharacterString>
    </gmd:description>
    <gmd:function>
      <gmd:CI_OnLineFunctionCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#CI_OnLineFunctionCode" codeListValue="download" codeSpace="eng">Download</gmd:CI_OnLineFunctionCode>
    </gmd:function>
  </gmd:CI_OnlineResource>
</gmd:onlineResource>
----
|
[source,xml]
----
<cit:onlineResource>
  <cit:CI_OnlineResource>
    <cit:linkage>
      <gco:CharacterString>http://example.com</gco:CharacterString>
    </cit:linkage>
    <cit:protocol>
      <gco:CharacterString>protocol</gco:CharacterString>
    </cit:protocol>
    <cit:applicationProfile>
      <gco:CharacterString>applicationProfile</gco:CharacterString>
    </cit:applicationProfile>
    <cit:name>
      <gco:CharacterString>name</gco:CharacterString>
    </cit:name>
    <cit:description>
      <gco:CharacterString>description</gco:CharacterString>
    </cit:description>
    <cit:function>
      <cit:CI_OnLineFunctionCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#CI_OnLineFunctionCode" codeListValue="download" codeSpace="eng">Download</cit:CI_OnLineFunctionCode>
    </cit:function>
  </cit:CI_OnlineResource>
</cit:onlineResource>
----



| [[dateStamp]] dateStamp
|
*   DefaultMetadata
*   CI_DateTypeCode
|
*   Name is now _dateInfo_
*   Namespace is now "mdb" from "gmd"
*   Now contains _cit:date_ and _cit:dateType_ elements instead of just a _gco:DateTime_ element
|
[source,xml]
----
<gmd:dateStamp>
  <gco:DateTime>2016-12-29T15:51:28.701+01:00</gco:DateTime>
</gmd:dateStamp>
----
|
[source,xml]
----
<mdb:dateInfo>
  <cit:date>
    <gco:DateTime>2016-12-29T15:52:26.827+01:00</gco:DateTime>
  </cit:date>
  <cit:dateType>
    <cit:CI_DateTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#CI_DateTypeCode" codeListValue="creation" codeSpace="eng">Creation</cit:CI_DateTypeCode>
  </cit:dateType>
</mdb:dateInfo>
----



| [[metadataStandardName]] metadataStandardName
|
*   DefaultMetadata
|
*   Namespace is now "mdb" from "gmd"
*   Combined with xref:metadataStandardVersion[metadataStandardVersion] to form the new _mdb:metadataStandard_ element
|
[source,xml]
----
<gmd:metadataStandardName>
  <gco:CharacterString>metadataStandardName</gco:CharacterString>
</gmd:metadataStandardName>
----
|
[source,xml]
----
<mdb:metadataStandard>
  <cit:CI_Citation>
    <cit:title>
      <gco:CharacterString>metadataStandardName</gco:CharacterString>
    </cit:title>
    <cit:edition>
      <gco:CharacterString>metadataStandardVersion</gco:CharacterString>
    </cit:edition>
  </cit:CI_Citation>
</mdb:metadataStandard>
----



| [[metadataStandardVersion]] metadataStandardVersion
|
*   DefaultMetadata
|
*   Namespace is now "mdb" from "gmd"
*   Combined with xref:metadataStandardName[metadataStandardName] to form the new _mdb:metadataStandard_ element
|
[source,xml]
----
<gmd:metadataStandardVersion>
  <gco:CharacterString>metadataStandardVersion</gco:CharacterString>
</gmd:metadataStandardVersion>
----
|
See xref:metadataStandardName[metadataStandardName] ISO 19115-3 XML example.



| [[spatialRepresentationInfo]] spatialRepresentationInfo
|
*   GO_Measure
*   GO_Measure19139 (new class)
*   DefaultDimension
|
*   Namespace is now "mdb" from "gmd"
*   Can contain a variety of difference spatial representation elements. The example used in this case is _MD_Georectified_
*   The namespace of these internal elements has changed from "gmd" to "msr".
*   Added support for more units of measurement for the _Measure_ element.
|
[source,xml]
----
<gmd:spatialRepresentationInfo>
  <gmd:MD_Georectified>
    <gmd:numberOfDimensions>
      <gco:Integer>2</gco:Integer>
    </gmd:numberOfDimensions>
    <gmd:axisDimensionProperties>
      <gmd:MD_Dimension>
        <gmd:dimensionName>
          <gmd:MD_DimensionNameTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_DimensionNameTypeCode" codeListValue="row">Row</gmd:MD_DimensionNameTypeCode>
        </gmd:dimensionName>
        <gmd:dimensionSize>
          <gco:Integer>7777</gco:Integer>
        </gmd:dimensionSize>
        <gmd:resolution>
          <gco:Measure uom="http://schemas.opengis.net/iso/19139/20070417/resources/uom/gmxUom.xml#xpointer(//*[@gml:id='m'])">10.0</gco:Measure>
        </gmd:resolution>
      </gmd:MD_Dimension>
    </gmd:axisDimensionProperties>
    <gmd:cellGeometry>
      <gmd:MD_CellGeometryCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_CellGeometryCode" codeListValue="area" codeSpace="eng">Area</gmd:MD_CellGeometryCode>
    </gmd:cellGeometry>
    <gmd:transformationParameterAvailability>
      <gco:Boolean>false</gco:Boolean>
    </gmd:transformationParameterAvailability>
    <gmd:checkPointAvailability>
      <gco:Boolean>false</gco:Boolean>
    </gmd:checkPointAvailability>
    <gmd:pointInPixel>
      <gmd:MD_PixelOrientationCode>upperRight</gmd:MD_PixelOrientationCode>
    </gmd:pointInPixel>
  </gmd:MD_Georectified>
</gmd:spatialRepresentationInfo>
----
|
[source,xml]
----
<mdb:spatialRepresentationInfo>
  <msr:MD_Georectified>
    <msr:numberOfDimensions>
      <gco:Integer>2</gco:Integer>
    </msr:numberOfDimensions>
    <msr:axisDimensionProperties>
      <msr:MD_Dimension>
        <msr:dimensionName>
          <msr:MD_DimensionNameTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_DimensionNameTypeCode" codeListValue="row">Row</msr:MD_DimensionNameTypeCode>
        </msr:dimensionName>
        <msr:dimensionSize>
          <gco:Integer>7777</gco:Integer>
        </msr:dimensionSize>
        <msr:resolution>
          <gco:Measure uom="http://schemas.opengis.net/iso/19139/20070417/resources/uom/gmxUom.xml#xpointer(//*[@gml:id='m'])">10.0</gco:Measure>
        </msr:resolution>
      </msr:MD_Dimension>
    </msr:axisDimensionProperties>
    <msr:cellGeometry>
      <mdb:MD_CellGeometryCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_CellGeometryCode" codeListValue="area" codeSpace="eng">Area</mdb:MD_CellGeometryCode>
    </msr:cellGeometry>
    <msr:transformationParameterAvailability>
      <gco:Boolean>false</gco:Boolean>
    </msr:transformationParameterAvailability>
    <msr:checkPointAvailability>
      <gco:Boolean>false</gco:Boolean>
    </msr:checkPointAvailability>
    <msr:pointInPixel>
      <msr:MD_PixelOrientationCode>upperRight</msr:MD_PixelOrientationCode>
    </msr:pointInPixel>
  </msr:MD_Georectified>
</mdb:spatialRepresentationInfo>
----



| [[referenceSystemInfo]] referenceSystemInfo
|
*   ReferenceSystemMetadata
*   DefaultIdentifier
|
*   Namespace is now "mdb" from "gmd"
*   Various namespace changes in wrapped elements
*   _RS_Identifier_ now deprecated, more generic _MD_Identifier_ used instead (includes support for _description_ element)
|
[source,xml]
----
<gmd:referenceSystemInfo>
  <gmd:MD_ReferenceSystem>
    <gmd:referenceSystemIdentifier>
      <gmd:RS_Identifier>
        <gmd:authority>
          <gmd:CI_Citation>
            ...
          </gmd:CI_Citation>
        </gmd:authority>
        <gmd:code>
          <gco:CharacterString>refSystemCode</gco:CharacterString>
        </gmd:code>
        <gmd:codeSpace>
          <gco:CharacterString>refSystemCodeSpace</gco:CharacterString>
        </gmd:codeSpace>
        <gmd:version>
          <gco:CharacterString>1.0</gco:CharacterString>
        </gmd:version>
      </gmd:RS_Identifier>
    </gmd:referenceSystemIdentifier>
  </gmd:MD_ReferenceSystem>
</gmd:referenceSystemInfo>
----
|
[source,xml]
----
<mdb:referenceSystemInfo>
  <mrs:MD_ReferenceSystem>
    <mrs:referenceSystemIdentifier>
      <mcc:MD_Identifier>
        <mcc:authority>
          <cit:CI_Citation>
            ...
          </cit:CI_Citation>
        </mcc:authority>
        <mcc:code>
          <gco:CharacterString>refSystemCode</gco:CharacterString>
        </mcc:code>
        <mcc:codeSpace>
          <gco:CharacterString>refSystemCodeSpace</gco:CharacterString>
        </mcc:codeSpace>
        <mcc:version>
          <gco:CharacterString>1.0</gco:CharacterString>
        </mcc:version>
        <mcc:description>
          <gco:CharacterString>refSystemDescription</gco:CharacterString>
        </mcc:description>
      </mcc:MD_Identifier>
    </mrs:referenceSystemIdentifier>
  </mrs:MD_ReferenceSystem>
</mdb:referenceSystemInfo>
----


| [[metadataExtensionInfo]] metadataExtensionInfo
|
*   DefaultMetadataExtensionInformation
*   DefaultExtendedElementInformation
|
*   Namespace is now "mdb" from "gmd"
*   Namespace of wrapped elements is now "mex" from "gmd"
*   _shortName_ and _domainCode_ elements removed and NOT remapped in ISO 19115-3
|
[source,xml]
----
<gmd:metadataExtensionInfo>
  <gmd:MD_MetadataExtensionInformation>
    <gmd:extensionOnLineResource>
      <gmd:CI_OnlineResource>
         ...
      </gmd:CI_OnlineResource>
    </gmd:extensionOnLineResource>
    <gmd:extendedElementInformation>
      <gmd:MD_ExtendedElementInformation>
        <gmd:name>
          <gco:CharacterString>extendedElementInfoName</gco:CharacterString>
        </gmd:name>
        <gmd:shortName>
          <gco:CharacterString>shortName</gco:CharacterString>
        </gmd:shortName>
        <gmd:domainCode>
          <gco:Integer>1234</gco:Integer>
        </gmd:domainCode>
        <gmd:definition>
          <gco:CharacterString>definition</gco:CharacterString>
        </gmd:definition>
        <gmd:obligation>
          <gmd:MD_ObligationCode>mandatory</gmd:MD_ObligationCode>
        </gmd:obligation>
        <gmd:condition>
          <gco:CharacterString>condition</gco:CharacterString>
        </gmd:condition>
        <gmd:dataType>
          <gmd:MD_DatatypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_DatatypeCode" codeListValue="metaClass">Meta class</gmd:MD_DatatypeCode>
        </gmd:dataType>
        <gmd:maximumOccurrence>
          <gco:Integer>1</gco:Integer>
        </gmd:maximumOccurrence>
        <gmd:domainValue>
          <gco:CharacterString>domainValue</gco:CharacterString>
        </gmd:domainValue>
        <gmd:parentEntity>
          <gco:CharacterString>parentEntity</gco:CharacterString>
        </gmd:parentEntity>
        <gmd:rule>
          <gco:CharacterString>rule</gco:CharacterString>
        </gmd:rule>
        <gmd:rationale>
          <gco:CharacterString>rationale</gco:CharacterString>
        </gmd:rationale>
      </gmd:MD_ExtendedElementInformation>
    </gmd:extendedElementInformation>
  </gmd:MD_MetadataExtensionInformation>
</gmd:metadataExtensionInfo>
----
|
[source,xml]
----
<mdb:metadataExtensionInfo>
  <mex:MD_MetadataExtensionInformation>
    <mex:extensionOnLineResource>
      <cit:CI_OnlineResource>
         ...
      </cit:CI_OnlineResource>
    </mex:extensionOnLineResource>
    <mex:extendedElementInformation>
      <mex:MD_ExtendedElementInformation>
        <mex:name>
          <gco:CharacterString>extendedElementInfoName</gco:CharacterString>
        </mex:name>
        <mex:definition>
          <gco:CharacterString>definition</gco:CharacterString>
        </mex:definition>
        <mex:obligation>
          <mdb:MD_ObligationCode>mandatory</mdb:MD_ObligationCode>
        </mex:obligation>
        <mex:condition>
          <gco:CharacterString>condition</gco:CharacterString>
        </mex:condition>
        <mex:dataType>
          <mdb:MD_DatatypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_DatatypeCode" codeListValue="metaClass">Meta class</mdb:MD_DatatypeCode>
        </mex:dataType>
        <mex:maximumOccurrence>
          <gco:Integer>1</gco:Integer>
        </mex:maximumOccurrence>
        <mex:domainValue>
          <gco:CharacterString>domainValue</gco:CharacterString>
        </mex:domainValue>
        <mex:parentEntity>
          <gco:CharacterString>parentEntity</gco:CharacterString>
        </mex:parentEntity>
        <mex:rule>
          <gco:CharacterString>rule</gco:CharacterString>
        </mex:rule>
        <mex:rationale>
          <gco:CharacterString>rationale</gco:CharacterString>
        </mex:rationale>
      </mex:MD_ExtendedElementInformation>
    </mex:extendedElementInformation>
  </mex:MD_MetadataExtensionInformation>
</mdb:metadataExtensionInfo>
----



| [[CI_Citation]] CI_Citation
|
*   DefaultCitation
|
*   Namespace is now "cit" from "gmd"
*   _collectiveTitle_ element deprecated, no longer in ISO 19115-3
|
[source,xml]
----
<gmd:CI_Citation>
  <gmd:title>
    <gco:CharacterString>citationTitle</gco:CharacterString>
  </gmd:title>
  <gmd:alternateTitle>
    <gmx:Anchor xlink:href="http://example.com">alternateTitle</gmx:Anchor>
  </gmd:alternateTitle>
  <gmd:alternateTitle>
    <gco:CharacterString>alternateTitle</gco:CharacterString>
  </gmd:alternateTitle>
  <gmd:date>
    <gmd:CI_Date>
      ...
    </gmd:CI_Date>
  </gmd:date>
  <gmd:edition>
    <gco:CharacterString>edition</gco:CharacterString>
  </gmd:edition>
  <gmd:editionDate>
    <gco:DateTime>2017-01-06T22:11:00.389+01:00</gco:DateTime>
  </gmd:editionDate>
  <gmd:collectiveTitle>
    <gco:CharacterString>collectiveTitle</gco:CharacterString>
  </gmd:collectiveTitle>
</gmd:CI_Citation>
----
|
[source,xml]
----
<cit:CI_Citation>
  <cit:title>
    <gco:CharacterString>citationTitle</gco:CharacterString>
  </cit:title>
  <cit:alternateTitle>
    <gcx:Anchor xlink:href="http://example.com">alternateTitle</gcx:Anchor>
  </cit:alternateTitle>
  <cit:alternateTitle>
    <gco:CharacterString>alternateTitle</gco:CharacterString>
  </cit:alternateTitle>
  <cit:date>
    <cit:CI_Date>
      ...
    </cit:CI_Date>
  </cit:date>
  <cit:edition>
    <gco:CharacterString>edition</gco:CharacterString>
  </cit:edition>
  <cit:editionDate>
    <gco:DateTime>2017-01-06T22:11:00.389+01:00</gco:DateTime>
  </cit:editionDate>
</cit:CI_Citation>
----



| [[MD_DataIdentification]] MD_DataIdentification
|
*   AbstractIdentification
*   DefaultDataIdentification
|
*   Namespace is now "mri" from "gmd"
*   _spatialRepresentationType_ and _spatialResolution_ moved to be positioned after _resourceConstraints_ instead of after _pointOfContact_
*   _aggregationInfo_ replaced by _associatedResource_
*   New elements include _temporalResolution_, _additionalDocumentation_, and  _processingLevel_
*   NOTE: _temporalResolution_ element is not yet implemented due to a combination of time restrictions and difficulties with Duration interface not having proper adapters.
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[MD_Constraints]] MD_Constraints
|
*   DefaultConstraints
|
*   Namespace is now "mco" from "gmd"
*   Element type contained in _constraintApplicationScope_ changed to _MD_Scope_ from _DQ_Scope_
*   New elements include _graphic_, _reference_, _releasability_, and _responsibleParty_.
|
[source,xml]
----
<gmd:MD_Constraints>
  <gmd:useLimitation>
    <gco:CharacterString>useLimitation</gco:CharacterString>
  </gmd:useLimitation>
  <gmd:constraintApplicationScope>
    <gmd:DQ_Scope/>
  </gmd:constraintApplicationScope>
</gmd:MD_Constraints>
----
|
[source,xml]
----
<mco:MD_Constraints>
  <mco:useLimitation>
    <gco:CharacterString>useLimitation</gco:CharacterString>
  </mco:useLimitation>
  <mco:constraintApplicationScope>
    <mmi:MD_Scope/>
  </mco:constraintApplicationScope>
  <mco:graphic>
    <mcc:MD_BrowseGraphic/>
  </mco:graphic>
  <mco:reference>
    <cit:CI_Citation/>
  </mco:reference>
  <mco:releasability>
    <mco:MD_Releasability/>
  </mco:releasability>
  <mco:responsibleParty>
    <cit:CI_Responsibility/>
  </mco:responsibleParty>
</mco:MD_Constraints>
----



| [[MD_BrowseGraphic]] MD_BrowseGraphic
|
*   DefaultBrowseGraphic
|
*   Namespace is now "mcc" from "gmd"
*   _fileName_ property is now stored as a _gco:characterString_ rather than a _gmd:URL_
*   New elements include _linkage_ and _imageConstraints_
|
[source,xml]
----
<gmd:MD_BrowseGraphic>
  <gmd:fileName>
    <gco:CharacterString>filename.png</gco:CharacterString>
  </gmd:fileName>
  <gmd:fileDescription>
    <gco:CharacterString>description</gco:CharacterString>
  </gmd:fileDescription>
  <gmd:fileType>
    <gcx:MimeFileType type="fileType">fileType</gcx:MimeFileType>
  </gmd:fileType>
</gmd:MD_BrowseGraphic>
----
|
[source,xml]
----
<mcc:MD_BrowseGraphic>
  <mcc:fileName>
    <gco:CharacterString>filename.png</gco:CharacterString>
  </mcc:fileName>
  <mcc:fileDescription>
    <gco:CharacterString>description</gco:CharacterString>
  </mcc:fileDescription>
  <mcc:fileType>
    <gcx:MimeFileType type="fileType">fileType</gcx:MimeFileType>
  </mcc:fileType>
  <mcc:linkage>
    <cit:CI_OnlineResource/>
  </mcc:linkage>
  <mcc:imageConstraints>
    <mco:MD_Constraints/>
  </mcc:imageConstraints>
</mcc:MD_BrowseGraphic>
----



| [[MD_MaintenanceInformation]] MD_MaintenanceInformation
|
*   DefaultMaintenanceInformation
|
*   Namespace is now "mmi" from "gmd"
*   Information stored in _dateOfNextUpdate_ moved into _maintenanceDate_
*   Information stored in _updateScope_ and _updateScopeDescription_ moved into _maintenanceScope_ 
|
[source,xml]
----
<gmd:MD_MaintenanceInformation>
  <gmd:maintenanceAndUpdateFrequency>
    <gmd:MD_MaintenanceFrequencyCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_MaintenanceFrequencyCode" codeListValue="annually">Annually</gmd:MD_MaintenanceFrequencyCode>
  </gmd:maintenanceAndUpdateFrequency>
  <gmd:dateOfNextUpdate>
    <gco:DateTime>2017-01-09T22:29:24.245+01:00</gco:DateTime>
  </gmd:dateOfNextUpdate>
  <gmd:updateScope>
    <gmd:MD_ScopeCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_ScopeCode" codeListValue="application">Application</gmd:MD_ScopeCode>
  </gmd:updateScope>
  <gmd:updateScopeDescription>
    <gmd:MD_ScopeDescription>
      <gmd:dataset>
        <gco:CharacterString>dataset</gco:CharacterString>
      </gmd:dataset>
    </gmd:MD_ScopeDescription>
  </gmd:updateScopeDescription>
</gmd:MD_MaintenanceInformation>
----
|
[source,xml]
----
<mmi:MD_MaintenanceInformation>
  <mmi:maintenanceAndUpdateFrequency>
    <mmi:MD_MaintenanceFrequencyCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_MaintenanceFrequencyCode" codeListValue="annually">Annually</mmi:MD_MaintenanceFrequencyCode>
  </mmi:maintenanceAndUpdateFrequency>
  <mmi:maintenanceDate>
    <cit:CI_Date>
      <cit:date>
        <gco:DateTime>2017-01-09T22:29:24.245+01:00</gco:DateTime>
      </cit:date>
      <cit:dateType>
        <cit:CI_DateTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#CI_DateTypeCode" codeListValue="nextUpdate" codeSpace="eng">Next update</cit:CI_DateTypeCode>
      </cit:dateType>
    </cit:CI_Date>
  </mmi:maintenanceDate>
  <mmi:maintenanceScope>
    <mmi:MD_Scope>
      <mmi:level>
        <mcc:MD_ScopeCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_ScopeCode" codeListValue="application">Application</mcc:MD_ScopeCode>
      </mmi:level>
        <mmi:levelDescription>
          <mmi:MD_ScopeDescription>
            <mmi:dataset>
              <gco:CharacterString>dataset</gco:CharacterString>
            </mmi:dataset>
          </mmi:MD_ScopeDescription>
        </mmi:levelDescription>
    </mmi:MD_Scope>
  </mmi:maintenanceScope>
</mmi:MD_MaintenanceInformation>
----



| [[MD_Format]] MD_Format
|
*   DefaultFormat
|
*   Namespace is now "mrd" from "gmd"
*   _specification_, _name_, and _version_ information moved into new _formatSpecificationCitation_ element, which contains a xref:CI_Citation[CI_Citation]
*   New _medium_ element
|
[source,xml]
----
<gmd:MD_Format>
  <gmd:name>
    <gco:CharacterString>name</gco:CharacterString>
  </gmd:name>
  <gmd:version>
    <gco:CharacterString>version</gco:CharacterString>
  </gmd:version>
  <gmd:amendmentNumber>
    <gco:CharacterString>amendmentNumber</gco:CharacterString>
  </gmd:amendmentNumber>
  <gmd:specification>
    <gco:CharacterString>specification</gco:CharacterString>
  </gmd:specification>
  <gmd:fileDecompressionTechnique>
    <gco:CharacterString>decompressionTechnique</gco:CharacterString>
  </gmd:fileDecompressionTechnique>
</gmd:MD_Format>
----
|
[source,xml]
----
<mrd:MD_Format>
  <mrd:formatSpecificationCitation>
    <cit:CI_Citation>
      <cit:title>
        <gco:CharacterString>specification</gco:CharacterString>
      </cit:title>
      <cit:alternateTitle>
        <gco:CharacterString>name</gco:CharacterString>
      </cit:alternateTitle>
      <cit:edition>
        <gco:CharacterString>version</gco:CharacterString>
      </cit:edition>
    </cit:CI_Citation>
  </mrd:formatSpecificationCitation>
  <mrd:amendmentNumber>
    <gco:CharacterString>amendmentNumber</gco:CharacterString>
  </mrd:amendmentNumber>
  <mrd:fileDecompressionTechnique>
    <gco:CharacterString>decompressionTechnique</gco:CharacterString>
  </mrd:fileDecompressionTechnique>
</mrd:MD_Format>
----



| [[MD_Keywords]] MD_Keywords
|
*   DefaultKeywords
|
*   Namespace is now "mrd" from "gmd"
*   New element, _keywordClass_
|
[source,xml]
----
<gmd:MD_Keywords>
  <gmd:keyword>
    <gco:CharacterString>keyword2</gco:CharacterString>
  </gmd:keyword>
  <gmd:keyword>
    <gco:CharacterString>keyword1</gco:CharacterString>
  </gmd:keyword>
  <gmd:type>
    <gmd:MD_KeywordTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_KeywordTypeCode" codeListValue="theme">Theme</gmd:MD_KeywordTypeCode>
  </gmd:type>
  <gmd:thesaurusName>
    <gmd:CI_Citation></gmd:CI_Citation>
  </gmd:thesaurusName>
</gmd:MD_Keywords>
----
|
[source,xml]
----
<mri:MD_Keywords>
  <mri:keyword>
    <gco:CharacterString>keyword2</gco:CharacterString>
  </mri:keyword>
  <mri:keyword>
    <gco:CharacterString>keyword1</gco:CharacterString>
  </mri:keyword>
  <mri:type>
    <mdb:MD_KeywordTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#MD_KeywordTypeCode" codeListValue="theme">Theme</mdb:MD_KeywordTypeCode>
  </mri:type>
  <mri:thesaurusName>
    <cit:CI_Citation/>
  </mri:thesaurusName>
  <mri:keywordClass>
    <mri:MD_KeywordClass>
      <mri:className>
        <gco:CharacterString>name</gco:CharacterString>
      </mri:className>
    </mri:MD_KeywordClass>
  </mri:keywordClass>
</mri:MD_Keywords>
----



| [[MD_AggregateInformation]] MD_AggregateInformation
|
*   AbstractIdentification
*   DefaultAssociatedResource
*   DefaultAggregateInformation
*   DS_InitiativeTypeCode
*   DS_AssociationTypeCode
|
*   Namespace is now "mri" from "gmd"
*   Replaced by _MD_AssociatedResource_
|
[source,xml]
----
<gmd:MD_AggregateInformation>
  <gmd:associationType>
    <gmd:DS_AssociationTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#DS_AssociationTypeCode" codeListValue="dependency">Dependency</gmd:DS_AssociationTypeCode>
  </gmd:associationType>
  <gmd:initiativeType>
    <gmd:DS_InitiativeTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#DS_InitiativeTypeCode" codeListValue="experiment">Experiment</gmd:DS_InitiativeTypeCode>
  </gmd:initiativeType>
  <gmd:aggregateDataSetName>
    <gmd:CI_Citation/>
  </gmd:aggregateDataSetName>
</gmd:MD_AggregateInformation>
----
|
[source,xml]
----
<mri:MD_AssociatedResource>
  <mri:name>
    <cit:CI_Citation/>
  </mri:name>
  <mri:associationType>
    <mri:DS_AssociationTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#DS_AssociationTypeCode" codeListValue="dependency">Dependency</mri:DS_AssociationTypeCode>
  </mri:associationType>
  <mri:initiativeType>
    <mri:DS_InitiativeTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#DS_InitiativeTypeCode" codeListValue="experiment">Experiment</mri:DS_InitiativeTypeCode>
  </mri:initiativeType>
</mri:MD_AssociatedResource>
----



| [[SV_OperationMetadata]] SV_OperationMetadata
|
*   DefaultOperationMetadata
|
*   _DCP_ element renamed to _distributedComputingPlatform_
|
[source,xml]
----
<srv:SV_OperationMetadata>
  <srv:operationName>
    <gco:CharacterString>operationName</gco:CharacterString>
  </srv:operationName>
  <srv:DCP>
    <srv:DCPList codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#DCPList" codeListValue="JAVA" codeSpace="eng">Java</srv:DCPList>
  </srv:DCP>
  <srv:operationDescription>
    <gco:CharacterString>operationDescription</gco:CharacterString>
  </srv:operationDescription>
  <srv:invocationName>
    <gco:CharacterString>invocationName</gco:CharacterString>
  </srv:invocationName>
  <srv:connectPoint>
    <gmd:CI_OnlineResource/>
  </srv:connectPoint>
</srv:SV_OperationMetadata>
----
|
[source,xml]
----
<srv:SV_OperationMetadata>
  <srv:operationName>
    <gco:CharacterString>operationName</gco:CharacterString>
  </srv:operationName>
  <srv:distributedComputingPlatform>
    <srv:DCPList codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codelists.xml#DCPList" codeListValue="JAVA" codeSpace="eng">Java</srv:DCPList>
  </srv:distributedComputingPlatform>
  <srv:operationDescription>
    <gco:CharacterString>operationDescription</gco:CharacterString>
  </srv:operationDescription>
  <srv:invocationName>
    <gco:CharacterString>invocationName</gco:CharacterString>
  </srv:invocationName>
  <srv:connectPoint>
    <cit:CI_OnlineResource/>
  </srv:connectPoint>
</srv:SV_OperationMetadata>
----



| [[MD_Usage]] MD_Usage
|
*   DefaultUsage
|
*   Namespace is now "mri" from "gmd"
*   New elements _response_, _additionalDocumentation_, and _identifiedIssues_
|
[source,xml]
----
<gmd:MD_Usage>
  <gmd:specificUsage>
    <gco:CharacterString>specificUsage</gco:CharacterString>
  </gmd:specificUsage>
  <gmd:usageDateTime>
    <gco:DateTime>2017-01-11T21:01:15.837+01:00</gco:DateTime>
  </gmd:usageDateTime>
  <gmd:userDeterminedLimitations>
    <gco:CharacterString>userDeterminedLimitations</gco:CharacterString>
  </gmd:userDeterminedLimitations>
  <gmd:userContactInfo>
    <gmd:CI_ResponsibleParty></gmd:CI_ResponsibleParty>
  </gmd:userContactInfo>
</gmd:MD_Usage>
----
|
[source,xml]
----
<mri:MD_Usage>
  <mri:specificUsage>
    <gco:CharacterString>specificUsage</gco:CharacterString>
  </mri:specificUsage>
  <mri:usageDateTime>
    <gco:DateTime>2017-01-11T21:01:15.837+01:00</gco:DateTime>
  </mri:usageDateTime>
  <mri:userDeterminedLimitations>
    <gco:CharacterString>userDeterminedLimitations</gco:CharacterString>
  </mri:userDeterminedLimitations>
  <mri:userContactInfo>
    <cit:CI_Responsibility/>
  </mri:userContactInfo>
  <mri:response>
    <gco:CharacterString>response</gco:CharacterString>
  </mri:response>
  <mri:additionalDocumentation>
    <cit:CI_Citation/>
  </mri:additionalDocumentation>
  <mri:identifiedIssues>
    <cit:CI_Citation/>
  </mri:identifiedIssues>
</mri:MD_Usage>
----



| [[SV_CoupledResource]] SV_CoupledResource
|
*   DefaultCoupledResource
|
*   New elements include _resourceReference_, _resource_, and _operation_
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[MD_CoverageDescription]] MD_CoverageDescription
|
*   MD_CoverageContentTypeCode
*   DefaultCoverageDescription
|
*   Namespace is now "mrc" from "gmd"
*   New element _processingLevelCode_
*   New element _attributeGroup_ contains a _MD_AttributeGroup_ element that wraps previously existing properties _contentType_ and _dimension_
*   Namespace of _rangeElementDescription_ is now from "gmi" to "mrc"
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[MD_RangeDimension]] MD_RangeDimension
|
*   DefaultRangeDimension
|
*   Namespace is now "mrc" from "gmd"
*   New element _name_
*   Element _descriptor_ renamed to _description_
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[MD_SampleDimension]] MD_SampleDimension
|
*   DefaultRangeDimension
*   GO_Record (new adapter - used for _otherProperty_, may be incorrect)
*   DefaultRecord (changes made to enable adapter - may be incorrect)
|
*   Namespace is now "mrc" from "gmd"
*   New elements _scaleFactor_, _offset_, _meanValue_, _numberOfValues_, _standardDeviation_, _otherPropertyType_, _otherProperty_, and  _bitsPerValue_
*   NOTE: _sequenceIdentifier_ element may be incorrectly marshalled/unmarshalled (unable to figure out how to test and unable to find example)
|
[source,xml]
----
<gmd:MD_SampleDimension>
  <gmd:descriptor>
    <gco:CharacterString>descriptor</gco:CharacterString>
  </gmd:descriptor>
  <gmd:maxValue>
    <gco:Real>22.22</gco:Real>
  </gmd:maxValue>
  <gmd:minValue>
    <gco:Real>11.11</gco:Real>
  </gmd:minValue>
  <gmd:units>°F</gmd:units>
</gmd:MD_SampleDimension>
----
|
[source,xml]
----
<mrc:MD_SampleDimension>
  <mrc:description>
    <gco:CharacterString>descriptor</gco:CharacterString>
  </mrc:description>
  <mrc:maxValue>
    <gco:Real>22.22</gco:Real>
  </mrc:maxValue>
  <mrc:minValue>
    <gco:Real>11.11</gco:Real>
  </mrc:minValue>
  <mrc:units>°F</mrc:units>
  <mrc:scaleFactor>
    <gco:Real>1.0</gco:Real>
  </mrc:scaleFactor>
</mrc:MD_SampleDimension>
----



| [[MD_Band]] MD_Band
|
*   DefaultBand
|
*   Namespace is now "mrc" from "gmd"
*   New elements _boundMin_, _boundMax_, and _boundUnits_
*   Namespaces of elements _bandBoundaryDefinition_, _nominalSpatialResolution_, _transferFunctionType_, _transmittedPolarization_, and _detectedPolarization_ are now "mrc" from "gmi" 
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[MD_FeatureCatalogueDescription]] MD_FeatureCatalogueDescription
|
*   DefaultFeatureCatalogueDescription
*   MD_FeatureTypeInfo (new JAXB adapter)
|
*   Namespace is now "mrc" from "gmd"
*   _featureTypes_ renamed to _featureTypeInfo_, Java object type changed from GenericName to FeatureTypeInfo
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[MD_DigitalTransferOptions]] MD_DigitalTransferOptions
|
*   DefaultDigitalTransferOptions
|
*   Namespace is now "mrd" from "gmd"
*   _offLine_ element now has a multiplicity of 0..n
*   New _transferFrequency_ and _distributionFormat_ elements
|
[source,xml]
----

----
|
[source,xml]
----



----

| [[MD_Distribution]] MD_Distribution
|
*   DefaultDistribution
|
*   Namespace is now "mrd" from "gmd"
*   New element _description_
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[MD_Medium]] MD_Medium
|
*   DefaultMedium
|
*   Namespace is now "mrd" from "gmd"
*   _density_ element multiplicity changed from [0..n] to [0..1]
*   New _Identifier_ element of type xref:MD_Identifier[MD_Identifier]
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[MD_StandardOrderProcess]] MD_StandardOrderProcess
|
*   DefaultStandardOrderProcess
|
*   Namespace is now "mrd" from "gmd"
*   New elements _currency_, _orderOptionType_, and _orderOptions_
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[LI_Lineage]] LI_Lineage
|
*   DefaultLineage
|
*   Namespace is now "mrl" from "gmd"
*   New elements _scope_ and _additionalDocumentation_
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[LI_ProcessStep]] LI_ProcessStep
|
*   DefaultProcessStep
|
*   Namespace is now "mrl" from "gmd"
*   New elements _reference_ and _scope_
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[LI_Source]] LI_Source
|
*   DefaultSource
|
*   Namespace is now "mrl" from "gmd"
*   New elements _scope_, _sourceSpatialResolution_, _sourceReferenceSystem_, and _sourceMetadata_
*   Deprecated element _sourceExtent_ moved to xref:MD_Scope[MD_Scope] element _extent_
*   Deprecated element _scaleDenominator_ moved to xref:MD_Resolution[MD_Resolution] element _equivalentScale_
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[MD_ScopeDescription]] MD_ScopeDescription
|
*   DefaultScopeDescription
|
*   Namespace is now "mmi" from "gmd"
*   Implemented _features_, _attributes_, _featureInstances_, and _attributeInstances_ elements for ISO 19115-3 (NOTE: As far as I know, these elements existed in ISO 19139, but SIS did not have them writing to XML for some reason. I did not change that behavior, but it makes me concerned that they could possibly be buggy)
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[LE_ProcessStepReport]] LE_ProcessStepReport
|
*   DefaultProcessStepReport
|
*   Namespace is now "mrl" from "gmi"
*   Changed namespace of all attributes from "gmi" to "mrl" when marshalling ISO 19115-3. _LE_ProcessStepReport_ namespace remains unchanged at "gmi". Unsure how to proceed in fixing this for one standard without breaking the other.
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[MI_GeolocationInformation]] MI_GeolocationInformation
|
*   AbstractGeolocationInformation
|
*   Changed namespace of all attributes from "gmi" to "msr" when marshalling ISO 19115-3. MI_GeolocationInformation namespace remains unchanged at "gmi". Unsure how to proceed in fixing this for one standard without breaking the other.
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[MD_Dimension]] MD_Dimension
|
*   DefaultDimension
|
*   Namespace is now "msr" from "gmd"
*   _resolution_ element is now represented by a Measure object rather than a Double.
*   New elements _dimensionTitle_ and _dimensionDescription_
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[MD_ApplicationSchemaInformation]] MD_ApplicationSchemaInformation
|
*   DefaultApplicationSchemaInformation
|
*   Namespace is now "mdb" from "gmd"
*   _schemaAscii_ element implement for both ISO standards - was commented out before
*   _graphicsFile_ and _softwareDevelopmentFile_ elements implemented for ISO 19115-3. Unsure if these should also work with ISO 19139. SIS did not have them implemented by default.
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[MD_ExtendedElementInformation]] MD_ExtendedElementInformation
|
*   DefaultExtendedElementInformation
|
*   Namespace is now "mex" from "gmd"
*   _shortName_ and _domainCode_ elements deprecated (not mapped anywhere else for now)
*   _rationale_ element now supports only a single value rather than a collection
|
[source,xml]
----

----
|
[source,xml]
----

----



| [[MD_MetadataExtensionInformation]] MD_MetadataExtensionInformation
|
*   DefaultMetadataExtensionInformation
|
*   Namespace is now "mex" from "gmd"
|
[source,xml]
----

----
|
[source,xml]
----

----
|====================